version: '3.8'

# Dell Switch Port Tracer v2.1.3 - Development Docker Compose Configuration
# Features: Enhanced UI/UX, VLAN Management v2, Safe deployment structure
# Data Protection: Uses .env files and persistent volumes
# Production: Use docker-compose.prod.yml for production deployments

services:
  postgres:
    image: postgres:15-alpine
    container_name: dell-port-tracer-postgres-dev
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-port_tracer_db}
      POSTGRES_USER: ${POSTGRES_USER:-dell_tracer_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secure_password123}
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    ports:
      - "5432:5432"
    networks:
      - dell-port-tracer
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-dell_tracer_user} -d ${POSTGRES_DB:-port_tracer_db}']
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build: .
    container_name: dell-port-tracer-app-dev
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./backups:/app/backups
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dell-port-tracer
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5000/health']
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local

networks:
  dell-port-tracer:
    driver: bridge
