name: Build and Push Docker Image

on:
  push:
    branches:
      - development
    tags:
      - "v*.*.*"
      - "v*.*.*-alpha"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ---- PRODUCTION BUILD ----
      - name: Build and push Docker image (production)
        if: startsWith(github.ref, 'refs/tags/v') && !endsWith(github.ref, '-alpha') && github.event.base_ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # ---- STAGING BUILD ----
      - name: Build and push Docker image (staging)
        if: endsWith(github.ref, '-alpha') && github.event.base_ref == 'refs/heads/staging'
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile.staging
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # ---- DEVELOPMENT BUILD ----
      - name: Build and push Docker image (development)
        if: github.ref == 'refs/heads/development'
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile.dev
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:dev-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
