name: Build and Push Docker Image

on:
  push:
    branches:
      - development
    tags:
      - "v*.*.*"
      - "v*.*.*-alpha"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ---- PRODUCTION BUILD ----
      - name: Build and push Docker image (production)
        id: prod
        if: startsWith(github.ref, 'refs/tags/v') && !endsWith(github.ref, '-alpha')
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # ---- STAGING BUILD ----
      - name: Build and push Docker image (staging)
        id: staging
        if: startsWith(github.ref, 'refs/tags/v') && endsWith(github.ref, '-alpha')
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile.staging
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # ---- DEVELOPMENT BUILD ----
      - name: Build and push Docker image (development)
        id: dev
        if: github.ref == 'refs/heads/development'
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile.dev
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:dev-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # ---- SANITY CHECK ----
      - name: Fail if no build condition matched
        if: ${{ !steps.prod.conclusion && !steps.staging.conclusion && !steps.dev.conclusion }}
        run: |
          echo "❌ No matching condition found for ref: ${{ github.ref }}"
          exit 1
